#!/bin/sh
bspc config top_padding 0

$HOME/.config/sxhkd/launch.sh
$HOME/.config/polybar/launch.sh

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "#d9a67e"
bspc config normal_border_color "#2f3439"

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a Screenkey manage=off
